[project]
name = "models-under-pressure"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Arrrlex", email = "me+github@alexmck.com" }
]
requires-python = ">=3.10"
dependencies = [
    "torch<2.3",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "pre-commit>=3.5.0",
    "pyright>=1.1.394",
]
