name: linear_then_softmax
hyperparams:
  temperature: 5
  batch_size: 16
  epochs: 200
  optimizer_args:
    lr: 5e-3
    weight_decay: 1e-3
  final_lr: 1e-4
  gradient_accumulation_steps: 4
  patience: 10
