model:
  name: meta-llama/Llama-3.2-1B-Instruct

classifier_module:
  learning_rate: 1e-3
  weight_decay: 0.0
  scheduler_params: null
  class_weights: null
  label_smoothing: 0.0

dataloader:
  batch_size: 12
  shuffle: true

logger: null

trainer:
  max_epochs: 20
  accelerator: gpu
  devices: 1
  precision: bf16-true
  default_root_dir: ~/.cache/models-under-pressure
  accumulate_grad_batches: 1
