_target_: models_under_pressure.probes.pytorch_probes.PytorchProbe
_llm: ???
layer: ???
aggregator:
  _target_: models_under_pressure.interfaces.activations.Aggregator
  preprocessor: ${preprocessor}
  postprocessor: ${postprocessor}
_classifier:
  _target_: models_under_pressure.probes.pytorch_classifiers.PytorchLinearClassifier
  training_args:
    batch_size: 16
    epochs: 10
    learning_rate: 0.001
    weight_decay: 0.01
