
model_name: "meta-llama/Llama-3.3-70B-Instruct"
training_data: "prompts_13_03_25_gpt-4o_filtered.jsonl"
batch_size: 4
cv_folds: 5
best_layer: 31
layers: [5, 6]
max_samples: null
use_test_set: false
experiments_to_run:
  - generalisation_heatmap

probes:
  - name: "sklearn_probe"
    preprocessor: "mean"
    postprocessor: "sigmoid"
  - name: "pytorch_per_token_probe"
    preprocessor: "mean"
    postprocessor: "sigmoid"

best_probe:
  name: "sklearn_probe"
  preprocessor: "mean"
  postprocessor: "sigmoid"

baseline_models:
  - llama-1b
  - gemma-1b

variation_types:
  - prompt_style
  - tone
  - language
  - length
