anthropic: data/evals/test/anthropic_test_balanced_jul_30.jsonl
toolace: data/evals/test/toolace_test_balanced_jul_30.jsonl
mt: data/evals/test/mt_test_balanced_jul_30.jsonl
mts: data/evals/test/mts_test_balanced_jul_30.jsonl
mental_health: data/evals/test/mental_health_test_balanced_jul_30.jsonl
redteaming: data/evals/test/redteaming_test_balanced_jul_30.jsonl
